#!/usr/bin/env python3

import psycopg2
from db_ops import connect_to_db
from objects.item import Item
from operations.writer import Writer

def create_table():
    try:
        conn = connect_to_db()
        cursor = conn.cursor()
        cursor.execute("""
                       CREATE TABLE IF NOT EXISTS inventory (
                       item_id integer PRIMARY KEY GENERATED by default as identity,
                       name varchar(255) NOT NULL,
                       count integer NOT NULL);
                       """)
        conn.close()
    except psycopg2.Error as err:
        print("Failed to create database: " + str(err))
        raise

def temp_add_items():
    item1 = Item("DemoItem", 10)
    item2 = Item("AnotherItem", 32)

    conn = connect_to_db()

    writer = Writer()
    writer.add_item(conn, item1)
    writer.add_item(conn, item2)
    conn.close()

if __name__ == "__main__":
    # input will go here
    create_table()
    temp_add_items()

