services:
  pyventory:
    build: .
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
        restart: true
  database:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=pyventory
    volumes:
      - C:/PyVentory/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d pyventory"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s